version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_basooki
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:generatedKey
    depends_on:
      - db
    networks:
      - laravel_network

  db:
    image: mysql:8
    container_name: laravel_basooki_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel_basooki
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network: